# Generated by Django 3.0.5 on 2020-06-21 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(max_length=100)),
                ('target_line', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('website_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_student', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=20)),
                ('adminssion_date', models.DateTimeField(auto_now_add=True)),
                ('dob', models.DateField(max_length=8)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], default='', max_length=6)),
                ('address', models.CharField(max_length=300)),
                ('father_name', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=50)),
                ('father_mobile_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_class', models.CharField(max_length=100)),
                ('monthly_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subjects', models.CharField(choices=[('python', 'PYTHON'), ('django', 'DJANGO'), ('java', 'JAVA'), ('dotnet', 'DOTNET'), ('node.js', 'NODE.JS')], max_length=50)),
                ('marks', models.CharField(max_length=100)),
                ('total_students', models.CharField(default='', max_length=50)),
                ('reg_no', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='EDApp.Students')),
            ],
        ),
    ]
