# Generated by Django 3.0.5 on 2020-06-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_class', models.CharField(max_length=100)),
                ('monthly_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subjects', models.CharField(max_length=100)),
                ('marks', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
