# Generated by Django 3.0.5 on 2020-06-21 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EDApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='reg_no',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='EDApp.Students'),
        ),
    ]
