# Generated by Django 3.0.5 on 2020-06-22 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EDApp', '0002_auto_20200622_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='reg_no',
            field=models.ForeignKey(default='registration_number', null=True, on_delete=django.db.models.deletion.CASCADE, to='EDApp.Students'),
        ),
    ]
