# Generated by Django 3.0.5 on 2020-06-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDApp', '0002_auto_20200611_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='subjects',
            field=models.CharField(choices=[('python', 'PYTHON'), ('django', 'DJANGO'), ('java', 'JAVA'), ('dotnet', 'DOTNET'), ('node.js', 'NODE.JS')], default='', max_length=50),
        ),
    ]
