# Generated by Django 3.0.5 on 2020-06-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDApp', '0003_auto_20200622_1320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='occupation',
            new_name='father_occupation',
        ),
        migrations.AddField(
            model_name='students',
            name='mother_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='students',
            name='mother_occupation',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='students',
            name='gender',
            field=models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE')], default='', max_length=6),
        ),
    ]
