# Generated by Django 3.0.5 on 2020-06-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDApp', '0003_auto_20200611_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_student', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=20)),
                ('adminssion_date', models.DateTimeField(auto_now_add=True)),
                ('dob', models.DateField(max_length=8)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], default='', max_length=6)),
                ('address', models.CharField(max_length=300)),
                ('father_name', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=50)),
                ('father_mobile_number', models.CharField(max_length=20)),
            ],
        ),
    ]
