# Generated by Django 3.0.5 on 2020-06-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDApp', '0004_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='total_students',
            field=models.CharField(default='', max_length=50),
        ),
    ]
