# Generated by Django 3.0.5 on 2020-06-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDApp', '0004_auto_20200622_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='students',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
