# Generated by Django 3.0.5 on 2020-06-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDApp', '0006_auto_20200622_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_employee', models.CharField(max_length=100)),
                ('joining_date', models.DateField(max_length=10)),
                ('dob', models.DateField(max_length=10)),
                ('Employee_type', models.CharField(choices=[('Teaching Staff', 'TEACHING STAFF'), ('Non-Teaching', 'NON-TEACHING')], max_length=30)),
                ('monthly_salary', models.IntegerField()),
                ('mobile_number', models.CharField(max_length=20)),
                ('father_name', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE')], max_length=6)),
                ('email', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
