# Generated by Django 3.0.5 on 2020-07-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDApp', '0008_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='expense',
            field=models.FloatField(default=''),
        ),
        migrations.AlterField(
            model_name='account',
            name='income',
            field=models.FloatField(default=''),
        ),
    ]
