# Generated by Django 3.0.5 on 2020-07-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDApp', '0010_auto_20200706_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Present', 'PRESENT'), ('Absent', 'ABSENT'), ('Leave', 'LEAVE')], default='', max_length=100),
        ),
    ]
