# Generated by Django 3.0.5 on 2020-07-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDApp', '0012_auto_20200716_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='adminssion_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
